from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMinimumSize(QtCore.QSize(350, 72))
        MainWindow.setMaximumSize(QtCore.QSize(350, 72))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.testLabel = QtWidgets.QLabel(self.centralwidget)
        self.testLabel.setText("")
        self.testLabel.setObjectName("testLabel")
        self.gridLayout_2.addWidget(self.testLabel, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 21))
        self.menubar.setObjectName("menubar")
        self.menuProgram = QtWidgets.QMenu(self.menubar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuLab1 = QtWidgets.QMenu(self.menubar)
        self.menuLab1.setObjectName("menuLab1")
        self.menuLab2 = QtWidgets.QMenu(self.menubar)
        self.menuLab2.setObjectName("menuLab2")
        self.menuLab3 = QtWidgets.QMenu(self.menubar)
        self.menuLab3.setObjectName("menuLab3")
        self.menuLab4 = QtWidgets.QMenu(self.menubar)
        self.menuLab4.setObjectName("menuLab4")
        self.menuLab5 = QtWidgets.QMenu(self.menubar)
        self.menuLab5.setObjectName("menuLab5")
        self.menuLab6 = QtWidgets.QMenu(self.menubar)
        self.menuLab6.setObjectName("menuLab6")
        MainWindow.setMenuBar(self.menubar)
        self.actionO_programie = QtWidgets.QAction(MainWindow)
        self.actionO_programie.setObjectName("actionO_programie")
        self.actionOtworz = QtWidgets.QAction(MainWindow)
        self.actionOtworz.setObjectName("actionOtworz")
        self.actionZapisz = QtWidgets.QAction(MainWindow)
        self.actionZapisz.setObjectName("actionZapisz")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionKonwersja_do_obrazu_szaroodcieniowego = QtWidgets.QAction(MainWindow)
        self.actionKonwersja_do_obrazu_szaroodcieniowego.setObjectName("actionKonwersja_do_obrazu_szaroodcieniowego")
        self.action3_kanaly_szaroodcieniowe = QtWidgets.QAction(MainWindow)
        self.action3_kanaly_szaroodcieniowe.setObjectName("action3_kanaly_szaroodcieniowe")
        self.actionKonwersja_RGB_do_HSV = QtWidgets.QAction(MainWindow)
        self.actionKonwersja_RGB_do_HSV.setObjectName("actionKonwersja_RGB_do_HSV")
        self.actionKonwersja_RGB_do_Lab = QtWidgets.QAction(MainWindow)
        self.actionKonwersja_RGB_do_Lab.setObjectName("actionKonwersja_RGB_do_Lab")
        self.actionNormalizacja = QtWidgets.QAction(MainWindow)
        self.actionNormalizacja.setObjectName("actionNormalizacja")
        self.actionEqualizacja = QtWidgets.QAction(MainWindow)
        self.actionEqualizacja.setObjectName("actionEqualizacja")
        self.actionNegacja = QtWidgets.QAction(MainWindow)
        self.actionNegacja.setObjectName("actionNegacja")
        self.actionPosteryzacja = QtWidgets.QAction(MainWindow)
        self.actionPosteryzacja.setObjectName("actionPosteryzacja")
        self.actionDuplikuj = QtWidgets.QAction(MainWindow)
        self.actionDuplikuj.setObjectName("actionDuplikuj")
        self.actionOperacje_sasiectwa = QtWidgets.QAction(MainWindow)
        self.actionOperacje_sasiectwa.setObjectName("actionOperacje_sasiectwa")
        self.actionDetekcja_kraw_dzi = QtWidgets.QAction(MainWindow)
        self.actionDetekcja_kraw_dzi.setObjectName("actionDetekcja_kraw_dzi")
        self.actionwyostrzanie_liniowe = QtWidgets.QAction(MainWindow)
        self.actionwyostrzanie_liniowe.setObjectName("actionwyostrzanie_liniowe")
        self.actionPrewitt = QtWidgets.QAction(MainWindow)
        self.actionPrewitt.setObjectName("actionPrewitt")
        self.actionUniwersalna = QtWidgets.QAction(MainWindow)
        self.actionUniwersalna.setObjectName("actionUniwersalna")
        self.actionFiltr_Medianowy = QtWidgets.QAction(MainWindow)
        self.actionFiltr_Medianowy.setObjectName("actionFiltr_Medianowy")
        self.actionOperacje_morfologiczne = QtWidgets.QAction(MainWindow)
        self.actionOperacje_morfologiczne.setObjectName("actionOperacje_morfologiczne")
        self.actionSzkieletyzacja = QtWidgets.QAction(MainWindow)
        self.actionSzkieletyzacja.setObjectName("actionSzkieletyzacja")
        self.actionThresholding = QtWidgets.QAction(MainWindow)
        self.actionThresholding.setObjectName("actionThresholding")
        self.actionAdaptive_Thresholding = QtWidgets.QAction(MainWindow)
        self.actionAdaptive_Thresholding.setObjectName("actionAdaptive_Thresholding")
        self.actionProgowanie_metod_Otsu = QtWidgets.QAction(MainWindow)
        self.actionProgowanie_metod_Otsu.setObjectName("actionProgowanie_metod_Otsu")
        self.actionWatershed = QtWidgets.QAction(MainWindow)
        self.actionWatershed.setObjectName("actionWatershed")
        self.actionHough = QtWidgets.QAction(MainWindow)
        self.actionHough.setObjectName("actionHough")
        self.menuProgram.addAction(self.actionO_programie)
        self.menuPlik.addAction(self.actionOtworz)
        self.menuPlik.addAction(self.actionZapisz)
        self.menuPlik.addAction(self.actionDuplikuj)
        self.menuLab1.addAction(self.actionHistogram)
        self.menuLab1.addAction(self.actionKonwersja_do_obrazu_szaroodcieniowego)
        self.menuLab1.addAction(self.action3_kanaly_szaroodcieniowe)
        self.menuLab1.addAction(self.actionKonwersja_RGB_do_HSV)
        self.menuLab1.addAction(self.actionKonwersja_RGB_do_Lab)
        self.menuLab2.addAction(self.actionNormalizacja)
        self.menuLab2.addAction(self.actionEqualizacja)
        self.menuLab2.addAction(self.actionNegacja)
        self.menuLab2.addAction(self.actionPosteryzacja)
        self.menuLab3.addAction(self.actionOperacje_sasiectwa)
        self.menuLab3.addAction(self.actionFiltr_Medianowy)
        self.menuLab4.addAction(self.actionOperacje_morfologiczne)
        self.menuLab4.addAction(self.actionSzkieletyzacja)
        self.menuLab5.addAction(self.actionHough)
        self.menuLab6.addAction(self.actionThresholding)
        self.menuLab6.addAction(self.actionAdaptive_Thresholding)
        self.menuLab6.addAction(self.actionProgowanie_metod_Otsu)
        self.menuLab6.addAction(self.actionWatershed)
        self.menubar.addAction(self.menuProgram.menuAction())
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuLab1.menuAction())
        self.menubar.addAction(self.menuLab2.menuAction())
        self.menubar.addAction(self.menuLab3.menuAction())
        self.menubar.addAction(self.menuLab4.menuAction())
        self.menubar.addAction(self.menuLab5.menuAction())
        self.menubar.addAction(self.menuLab6.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "APO"))
        self.menuProgram.setTitle(_translate("MainWindow", "Program"))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik"))
        self.menuLab1.setTitle(_translate("MainWindow", "Lab1"))
        self.menuLab2.setTitle(_translate("MainWindow", "Lab2"))
        self.menuLab3.setTitle(_translate("MainWindow", "Lab3"))
        self.menuLab4.setTitle(_translate("MainWindow", "Lab4"))
        self.menuLab5.setTitle(_translate("MainWindow", "Lab5"))
        self.menuLab6.setTitle(_translate("MainWindow", "Lab6"))
        self.actionO_programie.setText(_translate("MainWindow", "O programie"))
        self.actionOtworz.setText(_translate("MainWindow", "Otwórz"))
        self.actionZapisz.setText(_translate("MainWindow", "Zapisz"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionKonwersja_do_obrazu_szaroodcieniowego.setText(_translate("MainWindow", "Konwersja do obrazu szaroodcieniowego"))
        self.action3_kanaly_szaroodcieniowe.setText(_translate("MainWindow", "Rozlozenie na 3 kanaly szaroodcieniowe"))
        self.actionKonwersja_RGB_do_HSV.setText(_translate("MainWindow", "Konwersja RGB do HSV"))
        self.actionKonwersja_RGB_do_Lab.setText(_translate("MainWindow", "Konwersja RGB do Lab"))
        self.actionNormalizacja.setText(_translate("MainWindow", "Normalizacja"))
        self.actionEqualizacja.setText(_translate("MainWindow", "Equalizacja"))
        self.actionNegacja.setText(_translate("MainWindow", "Negacja"))
        self.actionPosteryzacja.setText(_translate("MainWindow", "Posteryzacja"))
        self.actionDuplikuj.setText(_translate("MainWindow", "Duplikuj"))
        self.actionOperacje_sasiectwa.setText(_translate("MainWindow", "Operacje Sąsiedztwa"))
        self.actionDetekcja_kraw_dzi.setText(_translate("MainWindow", "Detekcja krawędzi"))
        self.actionwyostrzanie_liniowe.setText(_translate("MainWindow", "Wyostrzanie liniowe"))
        self.actionPrewitt.setText(_translate("MainWindow", "Prewitt"))
        self.actionUniwersalna.setText(_translate("MainWindow", "Uniwersalna"))
        self.actionFiltr_Medianowy.setText(_translate("MainWindow", "Filtr Medianowy"))
        self.actionOperacje_morfologiczne.setText(_translate("MainWindow", "Operacje morfologiczne"))
        self.actionSzkieletyzacja.setText(_translate("MainWindow", "Szkieletyzacja"))
        self.actionThresholding.setText(_translate("MainWindow", "Thresholding"))
        self.actionAdaptive_Thresholding.setText(_translate("MainWindow", "Adaptive Thresholding"))
        self.actionProgowanie_metod_Otsu.setText(_translate("MainWindow", "Progowanie metodą Otsu"))
        self.actionWatershed.setText(_translate("MainWindow", "Watershed"))
        self.actionHough.setText(_translate("MainWindow", "Hough"))
