# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\sugil\OneDrive\Pulpit\APO\dialogs\Filtr Medianiowy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_medianDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(264, 174)
        Dialog.setMaximumSize(QtCore.QSize(264, 174))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("opcja_brzegowa")
        self.radioButton.setChecked(True)
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setObjectName("opcja_brzegowa_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setObjectName("opcja_brzegowa_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Filtr Medianowy"))
        self.label.setText(_translate("Dialog", "Rozmiar maski:"))
        self.comboBox.setItemText(0, _translate("Dialog", "3x3"))
        self.comboBox.setItemText(1, _translate("Dialog", "5x5"))
        self.comboBox.setItemText(2, _translate("Dialog", "7x7"))
        self.label_2.setText(_translate("Dialog", "Opcja brzegowa:"))
        self.radioButton.setText(_translate("Dialog", "Isolated"))
        self.radioButton_2.setText(_translate("Dialog", "Reflect"))
        self.radioButton_3.setText(_translate("Dialog", "Replicate"))
