from PyQt5 import QtCore, QtWidgets

class Ui_MorfologiaDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(324, 324)
        Dialog.setMaximumSize(324, 324)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.Cb_operation = QtWidgets.QComboBox(Dialog)
        self.Cb_operation.setObjectName("Cb_operation")
        self.Cb_operation.addItem("")
        self.Cb_operation.addItem("")
        self.Cb_operation.addItem("")
        self.Cb_operation.addItem("")
        self.verticalLayout_3.addWidget(self.Cb_operation)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Rbtn_elem1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.Rbtn_elem1.setObjectName("Rbtn_elem1")
        self.Rbtn_elem1.setChecked(True)
        self.verticalLayout_2.addWidget(self.Rbtn_elem1)
        self.Rbtn_elem2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.Rbtn_elem2.setObjectName("Rbtn_elem2")
        self.verticalLayout_2.addWidget(self.Rbtn_elem2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Rbtn_option1 = QtWidgets.QRadioButton(self.groupBox)
        self.Rbtn_option1.setObjectName("Rbtn_option1")
        self.verticalLayout.addWidget(self.Rbtn_option1)
        self.Rbtn_option1.setChecked(True)
        self.Rbtn_option2 = QtWidgets.QRadioButton(self.groupBox)
        self.Rbtn_option2.setObjectName("Rbtn_option2")
        self.verticalLayout.addWidget(self.Rbtn_option2)
        self.Rbtn_option3 = QtWidgets.QRadioButton(self.groupBox)
        self.Rbtn_option3.setObjectName("Rbtn_option3")
        self.verticalLayout.addWidget(self.Rbtn_option3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.Cb_size = QtWidgets.QComboBox(Dialog)
        self.Cb_size.setObjectName("Cb_size")
        self.Cb_size.addItem("")
        self.Cb_size.addItem("")
        self.Cb_size.addItem("")
        self.Cb_size.addItem("")
        self.verticalLayout_3.addWidget(self.Cb_size)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Operacje Morfologiczne"))
        self.label.setText(_translate("Dialog", "Operacja:"))
        self.Cb_operation.setItemText(0, _translate("Dialog", "Erozja"))
        self.Cb_operation.setItemText(1, _translate("Dialog", "Dylatacja"))
        self.Cb_operation.setItemText(2, _translate("Dialog", "Zamknięcie"))
        self.Cb_operation.setItemText(3, _translate("Dialog", "Otwarcie"))
        self.label_2.setText(_translate("Dialog", "Element strukturalny:"))
        self.Rbtn_elem1.setText(_translate("Dialog", "Romb"))
        self.Rbtn_elem2.setText(_translate("Dialog", "Kwadrat"))
        self.label_3.setText(_translate("Dialog", "Opcja brzegowa:"))
        self.Rbtn_option1.setText(_translate("Dialog", "Isolated"))
        self.Rbtn_option2.setText(_translate("Dialog", "Reflect"))
        self.Rbtn_option3.setText(_translate("Dialog", "Replicate"))
        self.label_4.setText(_translate("Dialog", "Rozmiar:"))
        self.Cb_size.setItemText(0, _translate("Dialog", "3x3"))
        self.Cb_size.setItemText(1, _translate("Dialog", "5x5"))
        self.Cb_size.setItemText(2, _translate("Dialog", "7x7"))
        self.Cb_size.setItemText(3, _translate("Dialog", "9x9"))
