from PyQt5 import QtCore, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 198)
        Dialog.setMinimumSize(QtCore.QSize(354, 198))
        Dialog.setMaximumSize(QtCore.QSize(354, 198))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 160, 156, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 161, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 80, 161, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.opcja_brzegowa = QtWidgets.QRadioButton(self.frame)
        self.opcja_brzegowa.setGeometry(QtCore.QRect(10, 0, 82, 17))
        self.opcja_brzegowa.setObjectName("opcja_brzegowa")
        self.opcja_brzegowa.setChecked(True)
        self.opcja_brzegowa_2 = QtWidgets.QRadioButton(self.frame)
        self.opcja_brzegowa_2.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.opcja_brzegowa_2.setObjectName("opcja_brzegowa_2")
        self.opcja_brzegowa_3 = QtWidgets.QRadioButton(self.frame)
        self.opcja_brzegowa_3.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.opcja_brzegowa_3.setObjectName("opcja_brzegowa_3")
        self.radio_btns_label = QtWidgets.QLabel(Dialog)
        self.radio_btns_label.setGeometry(QtCore.QRect(10, 60, 101, 16))
        self.radio_btns_label.setObjectName("radio_btns_label")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(210, 20, 131, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        font = self.textEdit.font()
        font.setPointSize(14)
        font.setWeight(25)
        self.textEdit.setFont(font)
        self.textEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setFont(font)
        self.textEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_2, 0, 1, 1, 1)
        self.textEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setFont(font)
        self.textEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_3, 0, 2, 1, 1)
        self.textEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_4.setFont(font)
        self.textEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_4, 1, 0, 1, 1)
        self.textEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.setFont(font)
        self.textEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_5, 1, 1, 1, 1)
        self.textEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_6.setFont(font)
        self.textEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_6, 1, 2, 1, 1)
        self.textEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_7.setObjectName("textEdit_7")
        self.textEdit_7.setFont(font)
        self.textEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_7, 2, 0, 1, 1)
        self.textEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_8.setFont(font)
        self.textEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_8, 2, 1, 1, 1)
        self.textEdit_9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_9.setFont(font)
        self.textEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.gridLayout.addWidget(self.textEdit_9, 2, 2, 1, 1)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 20))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Operacje Sąsiedztwa"))
        self.comboBox.setItemText(0, _translate("Dialog", "Blur"))
        self.comboBox.setItemText(1, _translate("Dialog", "Sobel"))
        self.comboBox.setItemText(2, _translate("Dialog", "Laplacian"))
        self.comboBox.setItemText(3, _translate("Dialog", "Canny"))
        self.comboBox.setItemText(4, _translate("Dialog", "Wyostrzanie 1"))
        self.comboBox.setItemText(5, _translate("Dialog", "Wyostrzanie 2"))
        self.comboBox.setItemText(6, _translate("Dialog", "Wyostrzanie 3"))
        self.comboBox.setItemText(7, _translate("Dialog", "Uniwersalna maska"))
        self.comboBox.setItemText(8, _translate("Dialog", "PrewittN"))
        self.comboBox.setItemText(9, _translate("Dialog", "PrewittS"))
        self.comboBox.setItemText(10, _translate("Dialog", "prewittW"))
        self.comboBox.setItemText(11, _translate("Dialog", "PrewittE"))
        self.comboBox.setItemText(12, _translate("Dialog", "PrewittNE"))
        self.comboBox.setItemText(13, _translate("Dialog", "PrewittNW"))
        self.comboBox.setItemText(14, _translate("Dialog", "PrewittSE"))
        self.comboBox.setItemText(15, _translate("Dialog", "PrewittSW"))
        self.opcja_brzegowa.setText(_translate("Dialog", "Isolated"))
        self.opcja_brzegowa_2.setText(_translate("Dialog", "Reflect"))
        self.opcja_brzegowa_3.setText(_translate("Dialog", "Replicate"))
        self.radio_btns_label.setText(_translate("Dialog", "Opcje brzegowe:"))
        self.label.setText(_translate("Dialog", "Operacja:"))
